[workspace]
members = ["00-multi", "01-handcrafted"]
resolver = "2"

[workspace.package]
name = "tedge-config-example"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
serde = {version = "1.0", features = ["derive"]}
toml = "0.8"
regex = "1.11"
